/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 16 02:33:34 GMT 2017
 */

package org.asynchttpclient.extras.simple;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.ByteBuffer;
import java.nio.ReadOnlyBufferException;
import org.asynchttpclient.extras.simple.ByteBufferBodyConsumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ByteBufferBodyConsumer_ESTest extends ByteBufferBodyConsumer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(4069);
      ByteBuffer byteBuffer1 = byteBuffer0.asReadOnlyBuffer();
      ByteBufferBodyConsumer byteBufferBodyConsumer0 = new ByteBufferBodyConsumer(byteBuffer1);
      // Undeclared exception!
      try { 
        byteBufferBodyConsumer0.consume(byteBuffer1);
        fail("Expecting exception: ReadOnlyBufferException");
      
      } catch(ReadOnlyBufferException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.HeapByteBufferR", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ByteBufferBodyConsumer byteBufferBodyConsumer0 = new ByteBufferBodyConsumer((ByteBuffer) null);
      // Undeclared exception!
      try { 
        byteBufferBodyConsumer0.consume((ByteBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.asynchttpclient.extras.simple.ByteBufferBodyConsumer", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ByteBufferBodyConsumer byteBufferBodyConsumer0 = new ByteBufferBodyConsumer((ByteBuffer) null);
      // Undeclared exception!
      try { 
        byteBufferBodyConsumer0.close();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.asynchttpclient.extras.simple.ByteBufferBodyConsumer", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(0);
      ByteBufferBodyConsumer byteBufferBodyConsumer0 = new ByteBufferBodyConsumer(byteBuffer0);
      byteBufferBodyConsumer0.close();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(4069);
      ByteBufferBodyConsumer byteBufferBodyConsumer0 = new ByteBufferBodyConsumer(byteBuffer0);
      // Undeclared exception!
      try { 
        byteBufferBodyConsumer0.consume(byteBuffer0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.HeapByteBuffer", e);
      }
  }
}
