/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 16 01:55:18 GMT 2017
 */

package org.asynchttpclient.filter;

import org.junit.Test;
import static org.junit.Assert.*;
import org.asynchttpclient.filter.FilterException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FilterException_ESTest extends FilterException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FilterException filterException0 = new FilterException("");
      FilterException filterException1 = new FilterException("I~&c", filterException0);
      assertFalse(filterException1.equals((Object)filterException0));
  }
}
