/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 16 01:12:32 GMT 2017
 */

package org.asynchttpclient.request.body.multipart.part;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import java.nio.charset.Charset;
import java.util.LinkedList;
import java.util.List;
import org.apache.tomcat.util.buf.Utf8Encoder;
import org.asynchttpclient.Param;
import org.asynchttpclient.request.body.multipart.ByteArrayPart;
import org.asynchttpclient.request.body.multipart.FilePart;
import org.asynchttpclient.request.body.multipart.part.ByteArrayMultipartPart;
import org.asynchttpclient.request.body.multipart.part.FileMultipartPart;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileLikeMultipartPart_ESTest extends FileLikeMultipartPart_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      LinkedList<Param> linkedList0 = new LinkedList<Param>();
      ByteArrayPart byteArrayPart0 = mock(ByteArrayPart.class, new ViolatedAssumptionAnswer());
      doReturn("u8O", (String) null).when(byteArrayPart0).getDispositionType();
      byte[] byteArray1 = new byte[3];
      byteArray1[0] = (byte)0;
      linkedList0.toArray();
      byteArray1[1] = (byte) (-101);
      byteArray1[2] = (byte)34;
      ByteArrayMultipartPart byteArrayMultipartPart0 = null;
      try {
        byteArrayMultipartPart0 = new ByteArrayMultipartPart(byteArrayPart0, byteArray1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.asynchttpclient.request.body.multipart.part.MultipartPart", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      Utf8Encoder utf8Encoder0 = new Utf8Encoder();
      Charset charset0 = utf8Encoder0.charset();
      ByteArrayPart byteArrayPart0 = mock(ByteArrayPart.class, new ViolatedAssumptionAnswer());
      doReturn("GL$TjW&8*jKRFo&:4P$", "GL$TjW&8*jKRFo&:4P$").when(byteArrayPart0).getFileName();
      doReturn(charset0, charset0, charset0, (Charset) null).when(byteArrayPart0).getCharset();
      doReturn("GL$TjW&8*jKRFo&:4P$").when(byteArrayPart0).getContentType();
      doReturn("", "GL$TjW&8*jKRFo&:4P$").when(byteArrayPart0).getDispositionType();
      doReturn("GL$TjW&8*jKRFo&:4P$", "").when(byteArrayPart0).getName();
      ByteArrayMultipartPart byteArrayMultipartPart0 = null;
      try {
        byteArrayMultipartPart0 = new ByteArrayMultipartPart(byteArrayPart0, byteArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.asynchttpclient.request.body.multipart.part.MultipartPart", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FilePart filePart0 = mock(FilePart.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(filePart0).getFileName();
      doReturn((File) null).when(filePart0).getFile();
      doReturn((String) null).when(filePart0).getContentId();
      doReturn((String) null).when(filePart0).getContentType();
      doReturn((List) null).when(filePart0).getCustomHeaders();
      doReturn((String) null).when(filePart0).getDispositionType();
      doReturn((String) null).when(filePart0).getName();
      doReturn((String) null).when(filePart0).getTransferEncoding();
      byte[] byteArray0 = new byte[1];
      FileMultipartPart fileMultipartPart0 = null;
      try {
        fileMultipartPart0 = new FileMultipartPart(filePart0, byteArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockRandomAccessFile", e);
      }
  }
}
