/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 13 17:40:33 GMT 2017
 */

package spark.examples.filter;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import spark.examples.filter.FilterExampleAttributes;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FilterExampleAttributes_ESTest extends FilterExampleAttributes_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FilterExampleAttributes filterExampleAttributes0 = new FilterExampleAttributes();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[8];
      FilterExampleAttributes.main(stringArray0);
  }
}
