/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 16 02:24:50 GMT 2017
 */

package org.asynchttpclient.extras.rxjava2;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.reactivex.Maybe;
import io.reactivex.MaybeEmitter;
import io.reactivex.functions.Function;
import io.reactivex.plugins.RxJavaPlugins;
import java.util.function.Supplier;
import org.asynchttpclient.AsyncHandler;
import org.asynchttpclient.AsyncHttpClient;
import org.asynchttpclient.Request;
import org.asynchttpclient.extras.rxjava2.DefaultRxHttpClient;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DefaultRxHttpClient_ESTest extends DefaultRxHttpClient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AsyncHttpClient asyncHttpClient0 = mock(AsyncHttpClient.class, new ViolatedAssumptionAnswer());
      DefaultRxHttpClient defaultRxHttpClient0 = new DefaultRxHttpClient(asyncHttpClient0);
      Request request0 = mock(Request.class, new ViolatedAssumptionAnswer());
      Supplier<AsyncHandler<Integer>> supplier0 = (Supplier<AsyncHandler<Integer>>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      Function<Object, Maybe<Integer>> function0 = (Function<Object, Maybe<Integer>>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(function0).apply(any());
      RxJavaPlugins.setOnMaybeAssembly(function0);
      Maybe<Integer> maybe0 = defaultRxHttpClient0.prepare(request0, (Supplier<? extends AsyncHandler<Integer>>) supplier0);
      assertNull(maybe0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AsyncHttpClient asyncHttpClient0 = mock(AsyncHttpClient.class, new ViolatedAssumptionAnswer());
      DefaultRxHttpClient defaultRxHttpClient0 = new DefaultRxHttpClient(asyncHttpClient0);
      Request request0 = mock(Request.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        defaultRxHttpClient0.prepare(request0, (Supplier<? extends AsyncHandler<String>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AsyncHttpClient asyncHttpClient0 = mock(AsyncHttpClient.class, new ViolatedAssumptionAnswer());
      DefaultRxHttpClient defaultRxHttpClient0 = new DefaultRxHttpClient(asyncHttpClient0);
      AsyncHandler<AsyncHandler<Integer>> asyncHandler0 = (AsyncHandler<AsyncHandler<Integer>>) mock(AsyncHandler.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        defaultRxHttpClient0.createBridge((MaybeEmitter<AsyncHandler<Integer>>) null, asyncHandler0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultRxHttpClient defaultRxHttpClient0 = null;
      try {
        defaultRxHttpClient0 = new DefaultRxHttpClient((AsyncHttpClient) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AsyncHttpClient asyncHttpClient0 = mock(AsyncHttpClient.class, new ViolatedAssumptionAnswer());
      DefaultRxHttpClient defaultRxHttpClient0 = new DefaultRxHttpClient(asyncHttpClient0);
      MaybeEmitter<Integer> maybeEmitter0 = (MaybeEmitter<Integer>) mock(MaybeEmitter.class, new ViolatedAssumptionAnswer());
      AsyncHandler<Integer> asyncHandler0 = (AsyncHandler<Integer>) mock(AsyncHandler.class, new ViolatedAssumptionAnswer());
      AsyncHandler<?> asyncHandler1 = defaultRxHttpClient0.createBridge(maybeEmitter0, asyncHandler0);
      assertNotNull(asyncHandler1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AsyncHttpClient asyncHttpClient0 = mock(AsyncHttpClient.class, new ViolatedAssumptionAnswer());
      DefaultRxHttpClient defaultRxHttpClient0 = new DefaultRxHttpClient(asyncHttpClient0);
      Request request0 = mock(Request.class, new ViolatedAssumptionAnswer());
      Supplier<AsyncHandler<Integer>> supplier0 = (Supplier<AsyncHandler<Integer>>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      Maybe<Integer> maybe0 = defaultRxHttpClient0.prepare(request0, (Supplier<? extends AsyncHandler<Integer>>) supplier0);
      assertNotNull(maybe0);
  }
}
