/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 15 21:07:29 GMT 2017
 */

package edu.illinois.starts.asm;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.illinois.starts.asm.Attribute;
import edu.illinois.starts.asm.ClassReader;
import edu.illinois.starts.asm.ClassVisitor;
import edu.illinois.starts.asm.ClassWriter;
import edu.illinois.starts.asm.FieldWriter;
import edu.illinois.starts.asm.Handle;
import edu.illinois.starts.asm.Item;
import edu.illinois.starts.asm.MethodWriter;
import edu.illinois.starts.asm.Type;
import edu.illinois.starts.asm.TypePath;
import java.io.BufferedInputStream;
import java.io.PipedInputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClassWriter_ESTest extends ClassWriter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(2706);
      // Undeclared exception!
      try { 
        classWriter0.visitAnnotation((String) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1678);
      ClassVisitor classVisitor0 = classWriter0.cv;
      classWriter0.cv = null;
      classWriter0.newMethodTypeItem("Y>[hFa;w)w_5qN");
      classWriter0.newLong(1678);
      classWriter0.invalidFrames = true;
      classWriter0.visitSource("Y>[hFa;w)w_5qN", "Y>[hFa;w)w_5qN");
      Handle handle0 = new Handle(1, "", "2>|T^p2)7cg2XG", "!81`wm0");
      handle0.toString();
      Object[] objectArray0 = new Object[0];
      classWriter0.newInvokeDynamicItem("Y>[hFa;w)w_5qN", "Y>[hFa;w)w_5qN", handle0, objectArray0);
      classWriter0.visitAnnotation("SourceFile", true);
      // Undeclared exception!
      try { 
        classWriter0.toByteArray();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-19));
      classWriter0.newField(", <ZA))mg)J", ", <ZA))mg)J", "");
      classWriter0.visitInnerClass("", "p_F}7'rYm+D/Pe8nB+}", ", <ZA))mg)J", 5);
      classWriter0.newInteger(5);
      classWriter0.newField("KwT4X+Rhc$C", "6pal", "KwT4X+Rhc$C");
      classWriter0.newUTF8("java/lang/Object");
      classWriter0.newClass(", <ZA))mg)J");
      classWriter0.toByteArray();
      classWriter0.newMethod("", "7.l4ac4#", "7.l4ac4#", true);
      classWriter0.visitInnerClass("", ", <ZA))mg)J", "6pal", 5);
      String[] stringArray0 = new String[7];
      stringArray0[0] = "";
      stringArray0[1] = "java/lang/Object";
      stringArray0[2] = "";
      stringArray0[3] = "iQf39lO=!4#|2_e:G";
      stringArray0[4] = "java/lang/Object";
      stringArray0[5] = "6pal";
      stringArray0[6] = "java/lang/Object";
      // Undeclared exception!
      try { 
        classWriter0.visitMethod(19, "iQf39lO=!4#|2_e:G", "p_F}7'rYm+D/Pe8nB+}", "7.l4ac4#", stringArray0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(247);
      Boolean boolean0 = Boolean.FALSE;
      FieldWriter fieldWriter0 = new FieldWriter(classWriter0, 1, "BootstrapMethods", "BootstrapMethods", "h?E&1R(d&;H(oA1:T", boolean0);
      classWriter0.lastField = fieldWriter0;
      classWriter0.newFieldItem("$q$G", "MZpD+n 5", "dJQ}O@}V#k0$f&2");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1019);
      // Undeclared exception!
      try { 
        classWriter0.visitField(13, (String) null, ")a,J(a", (String) null, ")a,J(a");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1678);
      ClassVisitor classVisitor0 = classWriter0.cv;
      classWriter0.cv = null;
      classWriter0.newMethodTypeItem("Y>[hFa;w)w_5qN");
      classWriter0.newLong(1678);
      classWriter0.visitSource("Y>[hFa;w)w_5qN", "Y>[hFa;w)w_5qN");
      Handle handle0 = new Handle(1, "", "2>|T^p2)7cg2XG", "!81`wm0");
      handle0.toString();
      classWriter0.index = (-785);
      Object[] objectArray0 = new Object[0];
      classWriter0.newInvokeDynamicItem("Y>[hFa;w)w_5qN", "Y>[hFa;w)w_5qN", handle0, objectArray0);
      classWriter0.visitAnnotation("SourceFile", true);
      classWriter0.toByteArray();
      classWriter0.addUninitializedType("SourceFile", 1678);
      classWriter0.newHandleItem(1235, "Y>[hFa;w)w_5qN", "!81`wm0", "");
      classWriter0.newConstItem("06Fx#|x*H]AJnAttzl");
      classWriter0.thisName = "!81`wm0";
      classWriter0.newNameTypeItem("{lO.\"*Ws^CX,uoR", "mJ/b");
      classWriter0.newMethodType("");
      // Undeclared exception!
      try { 
        classWriter0.getMergedType(1678, 1678);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1678
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1019);
      classWriter0.newDouble(0.0);
      String[] stringArray0 = new String[5];
      stringArray0[0] = "";
      stringArray0[1] = "RuntimeInvisibleAnnotations";
      stringArray0[2] = "";
      stringArray0[3] = "";
      stringArray0[4] = "";
      classWriter0.visit(1019, 30, "", "RuntimeInvisibleAnnotations", "", stringArray0);
      classWriter0.newFloat(30);
      classWriter0.visitOuterClass("", (String) null, "qv^Z;='TlQ&$H&J");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      FileSystemHandling.appendDataToFile((EvoSuiteFile) null, byteArray0);
      FileSystemHandling.appendLineToFile((EvoSuiteFile) null, "");
      ClassWriter classWriter0 = new ClassWriter(1219);
      FileSystemHandling.shouldAllThrowIOExceptions();
      Character character0 = Character.valueOf('\\');
      Character.getName(1596);
      Character.isSurrogate('Y');
      classWriter0.visitField(18, "jM |r$7s;=6>l7)n", "jM |r$7s;=6>l7)n", "", character0);
      classWriter0.newMethodType("dh^P72h)#:{8");
      classWriter0.addType("ConstantValue");
      classWriter0.newLong(1);
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      BufferedInputStream bufferedInputStream0 = null;
      try {
        bufferedInputStream0 = new BufferedInputStream(pipedInputStream0, (-3310));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Buffer size <= 0
         //
         verifyException("java.io.BufferedInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1140);
      Long long0 = new Long(1140);
      Long.compare((-199L), 32);
      classWriter0.newConstItem(long0);
      classWriter0.bootstrapMethodsCount = 604;
      classWriter0.thisName = "EnclosingMethod";
      classWriter0.newHandleItem(32, "mYQV", "mYQV", "mYQV");
      classWriter0.newMethodTypeItem("EnclosingMethod");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ClassReader classReader0 = new ClassReader("java/lang/Class");
      ClassWriter classWriter0 = new ClassWriter(classReader0, (-2105));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-404));
      // Undeclared exception!
      try { 
        classWriter0.newClassItem((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      classWriter0.visitInnerClass("P9T@<KGR8'p_P`|", "", "=j~.wfaL*t;b#yF^Hu", 0);
      classWriter0.newClassItem("=U/:vD'']MsT?;81nT");
      ClassWriter classWriter1 = new ClassWriter(2);
      classWriter1.newFloat(2);
      classWriter0.cv = (ClassVisitor) classWriter0;
      classWriter0.newClassItem("Y");
      classWriter0.visit(252, 16776960, "", "=j~.wfaL*t;b#yF^Hu", "P9T@<KGR8'p_P`|", (String[]) null);
      classWriter0.toByteArray();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-69));
      String[] stringArray0 = new String[4];
      stringArray0[0] = "bYJ[u-hUX";
      stringArray0[1] = "bYJ[u-hUX";
      stringArray0[2] = "o|7\"NKr";
      stringArray0[3] = "edu.illinois.starts.asm.Type";
      classWriter0.visit((-69), 9, "bYJ[u-hUX", "bYJ[u-hUX", "o|7\"NKr", stringArray0);
      // Undeclared exception!
      try { 
        classWriter0.getMergedType((-69), (-69));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-1366));
      classWriter0.newHandleItem((-1366), "Class file too large!", "Class file too large!", "Class file too large!");
      classWriter0.visitInnerClass("IS`heAee", "kX/x>f]4H7z:9RA9KO/", (String) null, (-1366));
      classWriter0.thisName = "Exceptions";
      classWriter0.newMethod("=ubGj*UfHqnOl<7{:", "Synthetic", "", true);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-4238));
      classWriter0.newClassItem("$.tHi7)IRst");
      classWriter0.addType("");
      classWriter0.addUninitializedType("", 1);
      classWriter0.newClass("(/+eC5Srh[_|haWyD0p");
      classWriter0.newFloat(889.0159F);
      // Undeclared exception!
      try { 
        classWriter0.newField((String) null, "w+]7[W&ym", "S~$");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(18);
      MethodWriter methodWriter0 = new MethodWriter(classWriter0, (-3208), "=Xv)&d n>?", "=Xv)&d n>?", "", (String[]) null, false, false);
      classWriter0.lastMethod = methodWriter0;
      byte[] byteArray0 = classWriter0.toByteArray();
      classWriter0.newMethod("", "", "", false);
      // Undeclared exception!
      try { 
        classWriter0.newConst(byteArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // value [B@1621155f
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-1222));
      classWriter0.newMethodType("xSyR/:/6s~@l=<<gT");
      classWriter0.visitOuterClass("xSyR/:/6s~@l=<<gT", "xSyR/:/6s~@l=<<gT", (String) null);
      classWriter0.visitSource((String) null, "");
      classWriter0.addUninitializedType("`;rUu", 14);
      String[] stringArray0 = new String[5];
      Double double0 = new Double(1);
      Double.isFinite((-1.0));
      classWriter0.newConst(double0);
      stringArray0[0] = "`;rUu";
      stringArray0[1] = "java/lang/Object";
      stringArray0[2] = "`;rUu";
      stringArray0[3] = "java/lang/Object";
      stringArray0[4] = "java/lang/Object";
      classWriter0.visit((-1222), (-1190), "java/lang/Object", (String) null, "java/lang/Object", stringArray0);
      classWriter0.newMethodItem("`;rUu", "", "Class file too large!", false);
      classWriter0.newInteger((-773));
      classWriter0.newLong((-1190));
      // Undeclared exception!
      try { 
        classWriter0.getMergedType(16777216, 220);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 16777216
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(4025);
      classWriter0.visitSource("8@{NVeMM*puK'LmG<v", "8@{NVeMM*puK'LmG<v");
      classWriter0.newHandle(4025, "", "", "");
      classWriter0.newHandleItem(11, "", ".MQ_^Lj wx^Wu03_bth", ".MQ_^Lj wx^Wu03_bth");
      Handle handle0 = new Handle(1631, "", "", "");
      FieldWriter fieldWriter0 = new FieldWriter(classWriter0, 267386880, ".MQ_^Lj wx^Wu03_bth", "8@{NVeMM*puK'LmG<v", "8@{NVeMM*puK'LmG<v", handle0);
      // Undeclared exception!
      try { 
        classWriter0.newConst(fieldWriter0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // value edu.illinois.starts.asm.FieldWriter@13
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1678);
      ClassVisitor classVisitor0 = classWriter0.cv;
      classWriter0.cv = null;
      Handle handle0 = new Handle(1, "", "2>|T^p2)7cg2XG", "!81`wm0");
      handle0.toString();
      Object[] objectArray0 = new Object[0];
      FieldWriter fieldWriter0 = new FieldWriter(classWriter0, 1678, "", "", "O@V", "!81`wm0");
      classWriter0.lastField = fieldWriter0;
      classWriter0.visitAnnotation("SourceFile", false);
      classWriter0.toByteArray();
      classWriter0.addUninitializedType("SourceFile", 1678);
      classWriter0.newHandleItem(1235, "+", "!81`wm0", "");
      classWriter0.newConstItem("06Fx#|x*H]AJnAttzl");
      classWriter0.thisName = "!81`wm0";
      classWriter0.newNameTypeItem("SourceFile", "mJ/b");
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      classWriter0.visitInnerClass("P9T@<KGR8'p_P`|", "", "=j~.wfaL*t;b#yF^Hu", 0);
      classWriter0.newClassItem("=U/:vD'']MsT?;81nT");
      ClassWriter classWriter1 = new ClassWriter(2);
      classWriter1.newFloat(2);
      classWriter0.cv = (ClassVisitor) classWriter1;
      classWriter0.addUninitializedType("P9T@<KGR8'p_P`|", 1);
      classWriter0.newClassItem("Y");
      classWriter0.visit(2, 16776960, "", "=j~.wfaL*t;b#yF^Hu", "=j~.wfaL*t;b#yF^Hu", (String[]) null);
      classWriter0.toByteArray();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1019);
      classWriter0.newDouble(0.0);
      String[] stringArray0 = new String[5];
      stringArray0[0] = "";
      stringArray0[1] = "RuntimeInvisibleAnnotations";
      stringArray0[2] = "";
      stringArray0[3] = "";
      stringArray0[4] = "";
      classWriter0.visit(1019, 30, "", "RuntimeInvisibleAnnotations", "", stringArray0);
      classWriter0.toByteArray();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-1222));
      classWriter0.newMethodType("xSyR/:/6s~@l=<<gT");
      classWriter0.visitOuterClass("xSyR/:/6s~@l=<<gT", "xSyR/:/6s~@l=<<gT", (String) null);
      classWriter0.addUninitializedType("`;rUu", 0);
      FileSystemHandling.setPermissions((EvoSuiteFile) null, false, false, true);
      String[] stringArray0 = new String[5];
      stringArray0[0] = "`;rUu";
      // Undeclared exception!
      try { 
        classWriter0.newUTF8((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      FileSystemHandling.createFolder((EvoSuiteFile) null);
      ClassWriter classWriter0 = new ClassWriter(24);
      FileSystemHandling.setPermissions((EvoSuiteFile) null, false, false, false);
      classWriter0.newClassItem("me  4*,l@=KGsm");
      String[] stringArray0 = new String[2];
      stringArray0[0] = "";
      stringArray0[1] = "";
      Handle handle0 = new Handle(24, "", "", "8T");
      classWriter0.newInvokeDynamicItem("", "", handle0, stringArray0);
      MethodWriter methodWriter0 = new MethodWriter(classWriter0, (-3740), "me  4*,l@=KGsm", "", "", stringArray0, false, false);
      classWriter0.lastMethod = methodWriter0;
      classWriter0.visitOuterClass("me  4*,l@=KGsm", "2H{X5l'TG^=t_+D'", ":/okkl|v[E-maE3");
      classWriter0.newUTF8("RuntimeVisibleTypeAnnotations");
      classWriter0.newConst(":/okkl|v[E-maE3");
      classWriter0.newMethodType("");
      Object[] objectArray0 = new Object[5];
      objectArray0[0] = (Object) "";
      objectArray0[1] = (Object) "";
      objectArray0[2] = (Object) classWriter0;
      objectArray0[3] = (Object) "";
      objectArray0[4] = (Object) classWriter0.lastMethod;
      // Undeclared exception!
      try { 
        classWriter0.newInvokeDynamic("+t<", "", handle0, objectArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // value edu.illinois.starts.asm.ClassWriter@1
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(2136);
      Handle handle0 = new Handle(0, (String) null, "", "");
      Object[] objectArray0 = new Object[8];
      objectArray0[0] = (Object) "java/lang/invoke/MethodType";
      objectArray0[1] = (Object) classWriter0;
      objectArray0[2] = (Object) "";
      objectArray0[3] = (Object) "java/lang/invoke/MethodType";
      objectArray0[4] = (Object) "java/lang/invoke/MethodType";
      handle0.toString();
      objectArray0[5] = (Object) null;
      objectArray0[6] = (Object) "java/lang/invoke/MethodType";
      objectArray0[7] = (Object) "";
      // Undeclared exception!
      try { 
        classWriter0.newNameType((String) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-1222));
      classWriter0.newMethodType("xSyR/:/6s~@l=<<gT");
      classWriter0.visitOuterClass("xSyR/:/6s~@l=<<gT", "xSyR/:/6s~@l=<<gT", (String) null);
      classWriter0.addUninitializedType("`;rUu", 0);
      String[] stringArray0 = new String[5];
      stringArray0[0] = "`;rUu";
      stringArray0[1] = "java/lang/Object";
      stringArray0[2] = null;
      stringArray0[3] = "java/lang/Object";
      stringArray0[4] = "java/lang/Object";
      // Undeclared exception!
      try { 
        classWriter0.visit((-1222), (-1146), "java/lang/Object", (String) null, "java/lang/Object", stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      classWriter0.visitSource((String) null, (String) null);
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        classWriter0.newMethod((String) null, "", "", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(65);
      // Undeclared exception!
      try { 
        classWriter0.newMethodTypeItem((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-2427));
      // Undeclared exception!
      try { 
        classWriter0.addType((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      classWriter0.visitMethod(186, "<M{`EW", "", "", (String[]) null);
      classWriter0.newClassItem("");
      classWriter0.visitAnnotation("", false);
      Byte byte0 = new Byte((byte) (-65));
      Byte.toUnsignedLong((byte) (-65));
      classWriter0.newConst(byte0);
      classWriter0.newClass("RuntimeVisibleTypeAnnotations");
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(2476);
      classWriter0.newClassItem("edu.illinois.starts.asm.Edge");
      classWriter0.newHandle(949, "&FBJa5(j|Q#+ KIeLO", "", "");
      classWriter0.newLong(0L);
      classWriter0.version = 292552704;
      classWriter0.addUninitializedType("edu.illinois.starts.asm.Edge", 0);
      classWriter0.newField("edu.illinois.starts.asm.Label", "", "T[|Ye)45Z");
      classWriter0.newNameType("?4)", ".PkS@>[&wR~t");
      // Undeclared exception!
      try { 
        classWriter0.newHandleItem(8, "", (String) null, "EFFFFFFFFGGFFFGGFFFEEFGFGFEEEEEEEEEEEEEEEEEEEEDEDEDDDDDCDCDEEEEEEEEEEEEEEEEEEEEBABABBBBDCFFFGGGEDCDCDCDCDCDCDCDCDCDCEEEEDDDDDDDCDCDCEFEFDDEEFFDEDEEEBDDBBDDDDDDCCCCCCCCEFEDDDCDCDEEEEEEEEEEFEEEEEEDDEEDDEE");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      byte[] byteArray0 = classWriter0.toByteArray();
      classWriter0.newField("~Y{Y6RVT:?Z#tH", "RuntimeVisibleAnnotations", "~Y{Y6RVT:?Z#tH");
      Object[] objectArray0 = new Object[9];
      Object object0 = new Object();
      objectArray0[0] = object0;
      objectArray0[1] = (Object) classWriter0;
      objectArray0[2] = (Object) byteArray0;
      objectArray0[3] = (Object) "RuntimeVisibleAnnotations";
      objectArray0[4] = (Object) classWriter0;
      objectArray0[5] = (Object) null;
      objectArray0[6] = (Object) "RuntimeVisibleAnnotations";
      objectArray0[7] = (Object) byteArray0;
      objectArray0[8] = (Object) null;
      // Undeclared exception!
      try { 
        classWriter0.newInvokeDynamic("", "~Y{Y6RVT:?Z#tH", (Handle) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-889275714));
      classWriter0.newMethodType("h");
      classWriter0.newMethodTypeItem("h");
      classWriter0.version = (-889275714);
      classWriter0.newMethodTypeItem("$|7");
      classWriter0.newMethod("", "", "", false);
      classWriter0.newInteger(91);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(13);
      Float float0 = new Float((double) 370);
      classWriter0.newConst(float0);
      // Undeclared exception!
      try { 
        classWriter0.getCommonSuperClass("INSn#_`YUz", "INSn#_`YUz");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: Class 'INSn#_`YUz.class' should be in target project, but could not be found!
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(731);
      classWriter0.toByteArray();
      classWriter0.newField("1", "1", "1");
      classWriter0.newField("1", "Ljava/lang/Synthetic;", "");
      Handle handle0 = new Handle(2190, "1", "", "");
      Object[] objectArray0 = new Object[3];
      objectArray0[0] = (Object) handle0;
      objectArray0[1] = (Object) "Ljava/lang/Synthetic;";
      objectArray0[2] = (Object) "";
      classWriter0.newInvokeDynamic("Ljava/lang/Synthetic;", "", handle0, objectArray0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(16);
      classWriter0.visitTypeAnnotation(16, (TypePath) null, "AAAAAAAAAAAAAAAABCLMMDDDDDEEEEEEEEEEEEEEEEEEEEAAAAAAAADDDDDEEEEEEEEEEEEEEEEEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAJJJJJJJJJJJJJJJJDOPAAAAAAGGGGGGGHIFBFAAFFAARQJJKKJJJJJJJJJJJJJJJJJJ", true);
      classWriter0.visitInnerClass(" fh p3H%%km", "", "", 16);
      String[] stringArray0 = new String[0];
      classWriter0.visit((-4387), 16, "", "", "", stringArray0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-2049));
      TypePath typePath0 = TypePath.fromString("RuntimeVisibleTypeAnnotations");
      // Undeclared exception!
      try { 
        classWriter0.visitTypeAnnotation((-2049), typePath0, (String) null, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1729);
      TypePath typePath0 = TypePath.fromString("A'$YCmS7vZsirq[");
      classWriter0.visitTypeAnnotation((-1957), typePath0, "", false);
      classWriter0.newNameType("BootstrapMethods", "A'$YCmS7vZsirq[");
      Attribute attribute0 = new Attribute("A'$YCmS7vZsirq[");
      classWriter0.visitAttribute(attribute0);
      String[] stringArray0 = new String[2];
      byte[] byteArray0 = new byte[0];
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(262144);
      ClassVisitor classVisitor0 = classWriter0.cv;
      classWriter0.cv = null;
      classWriter0.newUTF8("");
      classWriter0.newMethodTypeItem("edu.illinois.starts.asm.ClassWriter");
      classWriter0.newUTF8("edu.illinois.starts.asm.ClassWriter");
      classWriter0.newNameType("edu.illinois.starts.asm.ClassWriter", "");
      classWriter0.newUTF8("Class file too large!");
      // Undeclared exception!
      try { 
        classWriter0.getMergedType(0, 262144);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-395));
      classWriter0.newDouble(389.77190694);
      classWriter0.newDouble(389.77190694);
      // Undeclared exception!
      try { 
        classWriter0.getCommonSuperClass((String) null, (String) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.NullPointerException
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(16);
      classWriter0.newClassItem("Y");
      classWriter0.newClassItem("Y");
      Item item0 = classWriter0.newDouble(16);
      classWriter0.thisName = "Y";
      classWriter0.newHandleItem(16, "short", "SourceFile", "");
      item0.set(735);
      // Undeclared exception!
      try { 
        classWriter0.visitField(16, "RuntimeInvisibleTypeAnnotations", "RuntimeInvisibleTypeAnnotations", "RuntimeInvisibleTypeAnnotations", item0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // value edu.illinois.starts.asm.Item@9
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      Type type0 = Type.CHAR_TYPE;
      classWriter0.newDouble(1.0);
      Type[] typeArray0 = new Type[4];
      typeArray0[0] = type0;
      typeArray0[1] = type0;
      Type.getReturnType("BootstrapMethods");
      classWriter0.invalidFrames = true;
      typeArray0[2] = type0;
      typeArray0[3] = type0;
      Type type1 = Type.getMethodType(type0, typeArray0);
      Class<Boolean> class0 = Boolean.class;
      Type.getDescriptor(class0);
      Type.getType("{~jSy>|f(`I");
      classWriter0.newConst(type1);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      // Undeclared exception!
      try { 
        classWriter0.getMergedType(0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(3);
      classWriter0.threshold = 90;
      classWriter0.newField("InnerClasses", "", "");
      String[] stringArray0 = new String[4];
      String[] stringArray1 = new String[4];
      stringArray1[0] = "";
      stringArray1[1] = null;
      stringArray1[2] = null;
      stringArray1[3] = "";
      // Undeclared exception!
      try { 
        classWriter0.visit(9, 9, "InnerClasses", (String) null, (String) null, stringArray1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(64);
      Attribute attribute0 = new Attribute((String) null);
      Attribute attribute1 = attribute0.next;
      // Undeclared exception!
      try { 
        classWriter0.visitAttribute((Attribute) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(33);
      MethodWriter methodWriter0 = classWriter0.lastMethod;
      classWriter0.lastMethod = null;
      classWriter0.newMethodTypeItem("n,vfu0IMB9");
      Short short0 = new Short((short)0);
      classWriter0.newConstItem(short0);
      MethodWriter methodWriter1 = classWriter0.firstMethod;
      // Undeclared exception!
      try { 
        classWriter0.newConstItem((Object) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // value null
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-2142));
      classWriter0.newNameType("java/lang/invoke/MethodHandle", "java/lang/invoke/MethodHandle");
      classWriter0.newMethodItem("java/lang/invoke/MethodHandle", "java/lang/invoke/MethodHandle", "java/lang/invoke/MethodHandle", false);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1224736769);
      classWriter0.newFloat(158.2F);
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte)58;
      byteArray0[1] = (byte)0;
      byteArray0[2] = (byte) (-116);
      TypePath typePath0 = new TypePath(byteArray0, (byte)58);
      // Undeclared exception!
      try { 
        classWriter0.visitTypeAnnotation((-2083), typePath0, "", true);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 58
         //
         verifyException("edu.illinois.starts.asm.AnnotationWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(4096);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        classWriter0.newConst(object0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // value java.lang.Object@4a3215fe
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-5330));
      classWriter0.newLong(32L);
      MethodWriter methodWriter0 = classWriter0.lastMethod;
      classWriter0.firstMethod = null;
      classWriter0.newInteger((-5330));
      classWriter0.newHandleItem((-5330), "RuntimeVisibleAnnotations", "", "");
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(3);
      FileSystemHandling.createFolder((EvoSuiteFile) null);
      classWriter0.threshold = 3;
      String[] stringArray0 = new String[4];
      stringArray0[0] = null;
      stringArray0[2] = null;
      stringArray0[3] = null;
      classWriter0.visitAnnotation("Pyex", false);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-314));
      classWriter0.newNameTypeItem("", "");
      classWriter0.newMethodTypeItem("");
      String[] stringArray0 = new String[3];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "Q(&qR:1";
      // Undeclared exception!
      try { 
        classWriter0.visitMethod(0, "Q(&qR:1", "", "Q(&qR:1", stringArray0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(2535);
      // Undeclared exception!
      try { 
        classWriter0.newHandle((-659), (String) null, "", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      ClassWriter classWriter0 = null;
      try {
        classWriter0 = new ClassWriter((ClassReader) null, 267386880);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      classWriter0.visitInnerClass("P9T@<KGR8'p_P`|", "", "=j~.wfaL*t;b#yF^Hu", 0);
      classWriter0.newClassItem("=U/:vD'']MsT?;81nT");
      ClassWriter classWriter1 = new ClassWriter(2);
      classWriter1.newFloat(2);
      classWriter0.cv = (ClassVisitor) classWriter1;
      // Undeclared exception!
      try { 
        classWriter0.addUninitializedType((String) null, 252);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      TypePath typePath0 = TypePath.fromString("SourceFile");
      ClassVisitor classVisitor0 = classWriter0.cv;
      classWriter0.cv = null;
      TypePath.fromString("float");
      TypePath.fromString("SourceFile");
      classWriter0.visitTypeAnnotation(570, typePath0, "SourceFile", true);
      classWriter0.addUninitializedType("RuntimeInvisibleAnnotations", 2);
      String[] stringArray0 = new String[2];
      stringArray0[0] = "float";
      TypePath.fromString("RuntimeInvisibleAnnotations");
      stringArray0[1] = "SourceFile";
      classWriter0.visit(0, 1, "RuntimeInvisibleAnnotations", "float", "}8MG|h)2'IM*c]O[", stringArray0);
      // Undeclared exception!
      try { 
        classWriter0.newClass((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-3752));
      classWriter0.bootstrapMethodsCount = 782;
      classWriter0.newMethodItem("J6R{OP[IIPrXzM|e.", "RuntimeInvisibleAnnotations", "RuntimeInvisibleAnnotations", false);
      classWriter0.newClass("akZX@9+");
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-1317));
      classWriter0.newLong(0L);
      // Undeclared exception!
      try { 
        classWriter0.newFieldItem("", ">uJ`d,5N0@V8#(X", (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(54);
      // Undeclared exception!
      try { 
        classWriter0.getCommonSuperClass("Synthetic", "Synthetic");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: Class 'Synthetic.class' should be in target project, but could not be found!
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1235);
      // Undeclared exception!
      try { 
        classWriter0.newMethodItem((String) null, (String) null, (String) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(3423);
      classWriter0.visitOuterClass("Signature", "Signature", "Signature");
      classWriter0.newMethod("Signature", "Signature", "sVqnNUvOF'qUV", true);
      // Undeclared exception!
      try { 
        classWriter0.newMethodType((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1723);
      Object[] objectArray0 = new Object[8];
      objectArray0[0] = (Object) "";
      objectArray0[1] = (Object) "";
      classWriter0.newHandle(1723, "hF", "", "ai vE5EF9K#@]Dh");
      objectArray0[2] = (Object) "hF";
      objectArray0[3] = (Object) classWriter0;
      objectArray0[4] = (Object) null;
      objectArray0[5] = (Object) "";
      objectArray0[6] = (Object) "hF";
      objectArray0[7] = (Object) "hF";
      // Undeclared exception!
      try { 
        classWriter0.newInvokeDynamicItem("hF", "", (Handle) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(3);
      classWriter0.newFieldItem(";", "Signature", "");
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(13);
      classWriter0.newHandle(18, "RuntimeVisibleTypeAnnotations", "RuntimeVisibleTypeAnnotations", "");
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(6716);
      classWriter0.newHandle(0, "", "", "");
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      Handle handle0 = new Handle(0, "SFLt*TNB", "Deprecated", "void");
      Object[] objectArray0 = new Object[7];
      objectArray0[0] = (Object) "Deprecated";
      objectArray0[1] = (Object) "Deprecated";
      objectArray0[2] = (Object) "SFLt*TNB";
      objectArray0[3] = (Object) "Deprecated";
      objectArray0[4] = (Object) "void";
      Object object0 = new Object();
      objectArray0[5] = object0;
      objectArray0[6] = (Object) classWriter0;
      // Undeclared exception!
      try { 
        classWriter0.newInvokeDynamicItem("Deprecated", "Deprecated", handle0, objectArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // value java.lang.Object@1fe20fa3
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      Type type0 = Type.LONG_TYPE;
      classWriter0.newConst(type0);
      classWriter0.newNameType("RuntimeVisibleAnnotations", "RuntimeVisibleAnnotations");
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter((-925));
      Integer integer0 = new Integer((-925));
      classWriter0.visitField(710, "", "", "", integer0);
      classWriter0.newDouble((-925));
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1729);
      TypePath typePath0 = TypePath.fromString("A'$YCmS7vZsirq[");
      classWriter0.visitTypeAnnotation((-1957), typePath0, "BootstrapMethods", false);
      classWriter0.newNameType("BootstrapMethods", "A'$YCmS7vZsirq[");
      Attribute attribute0 = new Attribute("A'$YCmS7vZsirq[");
      String[] stringArray0 = new String[2];
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1678);
      ClassVisitor classVisitor0 = classWriter0.cv;
      classWriter0.cv = null;
      classWriter0.newMethodTypeItem("Y>[hFa;w)w_5qN");
      classWriter0.visitSource("Y>[hFa;w)w_5qN", "Y>[hFa;w)w_5qN");
      Handle handle0 = new Handle(1, "", "2>|T^p2)7cg2XG", "!81`wm0");
      handle0.toString();
      Object[] objectArray0 = new Object[0];
      classWriter0.newInvokeDynamicItem("Y>[hFa;w)w_5qN", "Y>[hFa;w)w_5qN", handle0, objectArray0);
      FieldWriter fieldWriter0 = new FieldWriter(classWriter0, 1678, "", "", "O@V", "!81`wm0");
      classWriter0.lastField = fieldWriter0;
      classWriter0.visitAnnotation("SourceFile", true);
      classWriter0.toByteArray();
      classWriter0.addUninitializedType("SourceFile", 1678);
      classWriter0.newHandleItem(1235, "+", "!81`wm0", "");
      classWriter0.newConstItem("06Fx#|x*H]AJnAttzl");
      classWriter0.thisName = "!81`wm0";
      classWriter0.newNameTypeItem("SourceFile", "mJ/b");
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      classWriter0.newMethodType("");
      classWriter0.newLong(0);
      classWriter0.newMethodItem("", "kLVC~", "GDS>X", true);
      String[] stringArray0 = new String[4];
      stringArray0[0] = "42-AR~c@//[";
      stringArray0[1] = "";
      stringArray0[2] = "42-AR~c@//[";
      stringArray0[3] = "TX~m}";
      classWriter0.visitMethod(0, "TX~m}", "42-AR~c@//[", "TX~m}", stringArray0);
      classWriter0.newMethodItem("kLVC~", "4BE", "TX~m}", true);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(0);
      classWriter0.invalidFrames = false;
      classWriter0.visitInnerClass("", "", "", 0);
      classWriter0.visitSource("=Vc:L_33MXv", "=Vc:L_33MXv");
      classWriter0.newMethod("", "jxu9XeN", "3QI}_", true);
      classWriter0.visitEnd();
      classWriter0.visitTypeAnnotation(2269, (TypePath) null, "", true);
      Handle handle0 = new Handle(2, "6CKw}U@<Qz_W2]jM$U", "{>+uBc", "jxu9XeN");
      Object[] objectArray0 = new Object[5];
      objectArray0[0] = (Object) "3QI}_";
      objectArray0[1] = (Object) "6CKw}U@<Qz_W2]jM$U";
      handle0.toString();
      Attribute attribute0 = new Attribute("3QI}_");
      byte[] byteArray0 = new byte[7];
      byteArray0[0] = (byte)2;
      byteArray0[1] = (byte)15;
      byteArray0[2] = (byte)81;
      byteArray0[3] = (byte) (-53);
      byteArray0[4] = (byte)14;
      byteArray0[5] = (byte)2;
      byteArray0[6] = (byte) (-12);
      ClassReader classReader0 = null;
      try {
        classReader0 = new ClassReader(byteArray0, (byte)2, 2269);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 8
         //
         verifyException("edu.illinois.starts.asm.ClassReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(4093);
      Object object0 = new Object();
      String string0 = ",";
      classWriter0.newMethodType(",");
      classWriter0.newFloat(2);
      Handle handle0 = new Handle((-120), ",", "RuntimeInvioibleAnnotations", "_u=jgQaFTh");
      Object[] objectArray0 = new Object[2];
      objectArray0[0] = (Object) handle0;
      Character.getName(1);
      handle0.toString();
      objectArray0[1] = (Object) classWriter0;
      // Undeclared exception!
      try { 
        classWriter0.newInvokeDynamicItem(",", ",", handle0, objectArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // value edu.illinois.starts.asm.ClassWriter@1
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      int int0 = 3;
      ClassWriter classWriter0 = new ClassWriter(3);
      classWriter0.newInteger(3);
      String string0 = "";
      classWriter0.threshold = 3;
      classWriter0.newField("Id6erClasses", "", "");
      String[] stringArray0 = new String[4];
      stringArray0[0] = null;
      stringArray0[1] = "Id6erClasses";
      String string1 = "InnerClasses";
      stringArray0[2] = "InnerClasses";
      stringArray0[3] = null;
      // Undeclared exception!
      try { 
        classWriter0.visitMethod(3, "Id6erClasses", (String) null, "", stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1019);
      classWriter0.newDouble(0.0);
      String[] stringArray0 = new String[5];
      stringArray0[0] = "";
      stringArray0[1] = "RuntimeInvisibleAnnotations";
      stringArray0[2] = "";
      stringArray0[2] = "";
      stringArray0[4] = "";
      // Undeclared exception!
      try { 
        classWriter0.visit(1019, 30, "", "RuntimeInvisibleAnnotations", "", stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.illinois.starts.asm.Item", e);
      }
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      String[] stringArray0 = new String[5];
      stringArray0[0] = "";
      stringArray0[1] = "RuntimeInvisibleAnnotations";
      stringArray0[3] = "";
      stringArray0[4] = "";
      ClassWriter classWriter0 = new ClassWriter((-639));
      Type type0 = Type.VOID_TYPE;
      Class<Character> class0 = Character.class;
      Type.getType(class0);
      classWriter0.visitField((-639), ".class", "RuntimeInvisibleAnnotations", "", type0);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(2706);
      classWriter0.newUTF8("{a915ZTG\"\"7a ");
      classWriter0.toByteArray();
      String[] stringArray0 = new String[7];
      stringArray0[0] = "{a915ZTG\"\"7a ";
      stringArray0[1] = "";
      stringArray0[2] = "{a915ZTG\"\"7a ";
      stringArray0[3] = "";
      stringArray0[4] = "{a915ZTG\"\"7a ";
      stringArray0[5] = "";
      stringArray0[6] = "";
      classWriter0.visit(0, 0, "{a915ZTG\"\"7a ", "{a915ZTG\"\"7a ", "", stringArray0);
      classWriter0.newInteger(2706);
      String string0 = "WasE";
      Handle handle0 = new Handle((-561), "", "WasE", "{a915ZTG\"\"7a ");
      Object[] objectArray0 = new Object[2];
      handle0.toString();
      objectArray0[0] = (Object) classWriter0;
      objectArray0[1] = (Object) "{a915ZTG\"\"7a ";
      // Undeclared exception!
      try { 
        classWriter0.newInvokeDynamic("{a915ZTG\"\"7a ", "{a915ZTG\"\"7a ", handle0, objectArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // value edu.illinois.starts.asm.ClassWriter@1
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      byte[] byteArray0 = new byte[10];
      byteArray0[0] = (byte)127;
      byteArray0[1] = (byte) (-79);
      byteArray0[4] = (byte)0;
      ClassReader classReader0 = new ClassReader(byteArray0);
      ClassWriter classWriter0 = new ClassWriter((byte)0);
      classWriter0.invalidFrames = false;
      classWriter0.addType("Q/}\"Y'3bQXY");
      ClassWriter classWriter1 = null;
      try {
        classWriter1 = new ClassWriter(classReader0, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("edu.illinois.starts.asm.ClassReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      ClassWriter classWriter0 = new ClassWriter(1678);
      ClassVisitor classVisitor0 = classWriter0.cv;
      classWriter0.cv = null;
      classWriter0.newMethodTypeItem("Y>[hFa;w)w_5qN");
      classWriter0.newLong(1678);
      classWriter0.visitSource("Y>[hFa;w)w_5qN", "Y>[hFa;w)w_5qN");
      Handle handle0 = new Handle(1, "", "2>|T^p2)7cg2XG", "!81`wm0");
      handle0.toString();
      Object[] objectArray0 = new Object[0];
      classWriter0.newInvokeDynamicItem("Y>[hFa;w)w_5qN", "Y>[hFa;w)w_5qN", handle0, objectArray0);
      classWriter0.visitAnnotation("SourceFile", true);
      classWriter0.toByteArray();
      classWriter0.addUninitializedType("SourceFile", 1678);
      classWriter0.newHandleItem(1235, "+", "!81`wm0", "");
      classWriter0.newConstItem("06Fx#|x*H]AJnAttzl");
      classWriter0.thisName = "!81`wm0";
      classWriter0.newNameTypeItem("{lO.\"*Ws^CX,uoR", "mJ/b");
      classWriter0.newMethodType("");
      // Undeclared exception!
      try { 
        classWriter0.getMergedType(1678, 1678);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1678
         //
         verifyException("edu.illinois.starts.asm.ClassWriter", e);
      }
  }
}
