/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 13 06:49:01 GMT 2017
 */

package com.github.scribejava.apis;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.scribejava.apis.SohuWeiboApi;
import com.github.scribejava.core.model.OAuth1RequestToken;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SohuWeiboApi_ESTest extends SohuWeiboApi_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SohuWeiboApi sohuWeiboApi0 = new SohuWeiboApi();
      OAuth1RequestToken oAuth1RequestToken0 = mock(OAuth1RequestToken.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(oAuth1RequestToken0).getToken();
      String string0 = sohuWeiboApi0.getAuthorizationUrl(oAuth1RequestToken0);
      assertEquals("http://api.t.sohu.com/oauth/authorize?oauth_token=null", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SohuWeiboApi sohuWeiboApi0 = new SohuWeiboApi();
      // Undeclared exception!
      try { 
        sohuWeiboApi0.getAuthorizationUrl((OAuth1RequestToken) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.scribejava.apis.SohuWeiboApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SohuWeiboApi sohuWeiboApi0 = SohuWeiboApi.instance();
      String string0 = sohuWeiboApi0.getRequestTokenEndpoint();
      assertEquals("http://api.t.sohu.com/oauth/request_token", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SohuWeiboApi sohuWeiboApi0 = SohuWeiboApi.instance();
      String string0 = sohuWeiboApi0.getAccessTokenEndpoint();
      assertEquals("http://api.t.sohu.com/oauth/access_token", string0);
  }
}
