/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 16 01:59:48 GMT 2017
 */

package org.asynchttpclient.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.asynchttpclient.util.DateUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DateUtils_ESTest extends DateUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      System.setCurrentTimeMillis(0L);
      long long0 = DateUtils.unpreciseMillisTime();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      System.setCurrentTimeMillis((-1535L));
      long long0 = DateUtils.unpreciseMillisTime();
      assertEquals((-1535L), long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      long long0 = DateUtils.unpreciseMillisTime();
      assertEquals(1392409281320L, long0);
  }
}
